security:
  oauth2:
    client:
      clientId: 5027999a-3cae-49ba-a66e-78fcbd417b46
      clientSecret: G1vW3hJ0gR1aU2cH8aP7jS4tE0wT8pI7eP4qT5kH8uX8fK0nD3
      accessTokenUri: https://api-sandbox.rabobank.nl/openapi/sandbox/oauth2/token
      userAuthorizationUri: https://api-sandbox.rabobank.nl/openapi/sandbox/oauth2/authorize
      scope: caf.fundsconfirmation.read,ais.balances.read,ais.transactions.read-90days,ais.transactions.read-history
    resource:
      userInfoUri: http://localhost:8080/me

spring:
  main:
    allow-bean-definition-overriding: true